title: stepping stone
email: stone.bastian@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi. I'm Bastian. I like to write code and annoy people with corny puns.
  This blog is about my thoughts on software development, agile practices, personal growth.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: wombat9000

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
